data:
  raw_path: data/raw/transactions.csv
  processed_path: data/processed/

features:
  include_geo: true
  rolling_window_hours: 24
  encode_categoricals: true

model:
  type: random_forest
  params:
    n_estimators: 100
    max_depth: 10

training:
  test_size: 0.2
  random_state: 42